# Header
menu:
  主页: /
  所有文章: /archives
  关于: /about

# SubNav
subnav:
  github: https://github.com/douxingxiang
  weibo: http://weibo.com/hitdxx
  #oschina: http://my.oschina.net/douxingxiang
  #jobbole: http://www.jobbole.com/members/douxingxiang
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt: 220
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /images/douxingxiang.jpg
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: github-io
#是否开启云标签
tagcloud: true

#是否开启友情链接
friends: false

#是否开启“关于我”。
aboutme: false